name: medicare-fastapi
type: gradio-space
sdk: docker

metadata:
  space_id: Chris4K/medicare-fastapi
  original_url: https://huggingface.co/spaces/Chris4K/medicare-fastapi

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"

# Updated: 2026-01-03 13:26:18
